# Generated by Django 5.0.6 on 2025-05-06 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabletimes',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='therapist.availabledate'),
        ),
        migrations.AddField(
            model_name='therapistdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specializations',
            name='therapist_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='therapist.therapistdetails'),
        ),
        migrations.AddField(
            model_name='languages',
            name='therapist_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='therapist.therapistdetails'),
        ),
    ]
