# Generated by Django 5.0.6 on 2025-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistdetails',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
