# Generated by Django 5.0.6 on 2025-08-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist", "0006_remove_specializations_specializations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specializations",
            name="specialization",
        ),
        migrations.AddField(
            model_name="specializations",
            name="specializations",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
