# Generated by Django 5.0.6 on 2025-08-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist", "0008_remove_specializations_specializations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("video_price", models.IntegerField()),
                ("audio_price", models.IntegerField()),
                ("chat_price", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="therapistdetails",
            name="tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="therapist.tier",
            ),
        ),
    ]
