# Generated by Django 5.0.6 on 2025-08-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist", "0009_tier_therapistdetails_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistdetails",
            name="tier",
            field=models.CharField(
                choices=[
                    ("bronze", "Bronze"),
                    ("silver", "Silver"),
                    ("gold", "Gold"),
                    ("platinum", "Platinum"),
                ],
                default="bronze",
                max_length=20,
            ),
        ),
    ]
