# Generated by Django 5.0.6 on 2025-08-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("therapist", "0010_alter_therapistdetails_tier"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tier",
        ),
    ]
