# Generated by Django 5.0.6 on 2025-09-23 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("therapist", "0011_delete_tier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="therapistdetails",
            name="address",
        ),
        migrations.RemoveField(
            model_name="therapistdetails",
            name="country",
        ),
        migrations.RemoveField(
            model_name="therapistdetails",
            name="dateOfBirth",
        ),
        migrations.RemoveField(
            model_name="therapistdetails",
            name="fullname",
        ),
        migrations.RemoveField(
            model_name="therapistdetails",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="therapistdetails",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="therapistdetails",
            name="state",
        ),
    ]
