# Generated by Django 5.0.6 on 2025-09-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapist", "0012_remove_therapistdetails_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistdetails",
            name="reject_reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
