# Generated by Django 5.0.6 on 2025-11-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0014_alter_therapistdetails_additionalcertificationdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistdetails',
            name='additionalCertificationDocument',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='therapistdetails',
            name='educationalCertificate',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistdetails',
            name='governmentIssuedID',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapistdetails',
            name='professionalLicense',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
