# Generated by Django 5.0.6 on 2025-11-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0015_alter_therapistdetails_additionalcertificationdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistdetails',
            name='additionalCertificationDocument',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='therapistdetails',
            name='educationalCertificate',
            field=models.FileField(max_length=500, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='therapistdetails',
            name='governmentIssuedID',
            field=models.FileField(max_length=500, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='therapistdetails',
            name='professionalLicense',
            field=models.FileField(max_length=500, upload_to='documents/'),
        ),
    ]
