# Generated by Django 5.0.6 on 2025-11-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0016_alter_therapistdetails_additionalcertificationdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistdetails',
            name='additionalCertificationDocument',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='therapistdetails',
            name='educationalCertificate',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='therapistdetails',
            name='governmentIssuedID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='therapistdetails',
            name='professionalLicense',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
