version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 mindease_bakend.asgi:application"
    volumes:
      - ./mindease_bakend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./mindease_bakend/.env
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DB_HOST=db  # Override .env to use service name instead of localhost

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mindease_db  # Must match DB_NAME in .env
      - POSTGRES_USER=postgres   # Must match DB_USER in .env
      - POSTGRES_PASSWORD=jasir snr  # Must match DB_PASSWORD in .env
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:  # ✅ Add this block
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: