version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 mindease_bakend.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - ./mindease_bakend:/app
      - /home/ubuntu/MindEase/backend/staticfiles:/app/staticfiles
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
