version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./mindease_bakend:/app
    env_file:
      - ./mindease_bakend/.env
