# Generated by Django 5.0.6 on 2025-07-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_call', models.IntegerField(default=0)),
                ('voice_call', models.IntegerField(default=0)),
                ('message', models.IntegerField(default=0)),
            ],
        ),
    ]
