# Generated by Django 5.0.6 on 2025-08-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierPriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze_video', models.IntegerField(default=700)),
                ('bronze_audio', models.IntegerField(default=500)),
                ('bronze_chat', models.IntegerField(default=300)),
                ('silver_video', models.IntegerField(default=1000)),
                ('silver_audio', models.IntegerField(default=700)),
                ('silver_chat', models.IntegerField(default=500)),
                ('gold_video', models.IntegerField(default=1500)),
                ('gold_audio', models.IntegerField(default=1000)),
                ('gold_chat', models.IntegerField(default=700)),
                ('platinum_video', models.IntegerField(default=2000)),
                ('platinum_audio', models.IntegerField(default=1500)),
                ('platinum_chat', models.IntegerField(default=1000)),
            ],
        ),
    ]
