# Generated by Django 5.0.6 on 2025-09-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0005_rename_silver_chatt_tierpriceconfig_silver_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinimumWithdrawAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
