# Generated by Django 5.0.6 on 2025-09-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admins", "0006_minimumwithdrawamount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minimumwithdrawamount",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
