# Generated by Django 5.0.6 on 2025-05-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_withdrawalrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
    ]
