# Generated by Django 5.0.6 on 2025-05-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_adminchat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminChat',
            new_name='AdminTherapistChat',
        ),
    ]
