# Generated by Django 5.0.6 on 2025-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='therapist_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='user_attended',
            field=models.BooleanField(default=False),
        ),
    ]
