# Generated by Django 5.0.6 on 2025-07-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_therapysession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
