# Generated by Django 5.0.6 on 2025-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_notification_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='therapistnotification',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
