# Generated by Django 5.0.6 on 2025-08-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_temporaryuser_remove_userdetails_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
