# Generated by Django 5.0.6 on 2025-08-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_temporaryuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='current_role',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
