# Generated by Django 5.0.6 on 2025-08-20 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_userdetails_current_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temporaryuser",
            name="username",
        ),
    ]
