# Generated by Django 5.0.6 on 2025-08-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_therapisttransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="login_method",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
