# Generated by Django 5.0.6 on 2025-08-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_userdetails_login_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_google_account',
            field=models.BooleanField(default=False),
        ),
    ]
