# Generated by Django 5.0.6 on 2025-08-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_userdetails_is_google_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='login_method',
        ),
    ]
