# Generated by Django 5.0.6 on 2025-10-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_remove_userdetails_login_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapysession",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
